/// <reference types="vitest" />
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
      "@shared": path.resolve(__dirname, "./shared"),
      "@electron": path.resolve(__dirname, "./.electron"),
    },
  },
  build: {
    outDir: "dist",
    emptyOutDir: true,
  },
  test: {
    include: ["tests/**/*.test.ts", "tests/**/*.test.tsx"],
    environment: "node",
    setupFiles: ["./tests/setup.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      include: [
        "src/utils/**/*.ts",
        "src/stores/**/*.ts",
        "src/hooks/**/*.ts",
        "src/hooks/**/*.tsx",
        "src/components/chrome/Omnibox.tsx",
        "src/components/chrome/TabBar.tsx",
        "src/components/chrome/Tab.tsx",
        "src/components/chrome/AppMenu.tsx",
        "src/components/chrome/BookmarksBar.tsx",
        "src/components/chrome/OmniboxSuggestions.tsx",
        "src/components/chrome/TabContextMenu.tsx",
        "src/components/chrome/BrowserContentArea.tsx",
        "src/components/overlays/FindInPage.tsx",
        "src/components/overlays/TranslationBar.tsx",
        "src/components/overlays/PageErrorOverlay.tsx",
        "src/components/overlays/AIPanel.tsx",
        "src/components/overlays/BookmarksPanel.tsx",
        "src/components/overlays/CommandPalette.tsx",
        "src/components/overlays/CommandPaletteIcon.tsx",
        "src/components/overlays/DownloadsShelf.tsx",
        "src/components/overlays/HistoryPanel.tsx",
        "src/components/overlays/PermissionPrompt.tsx",
        "src/components/overlays/SettingsPanel.tsx",
        "src/components/overlays/SidePanel.tsx",
        "src/components/overlays/SaveProposalCard.tsx",
        "src/components/overlays/SiteSkillsSection.tsx",
        "shared/**/*.ts",
        ".electron/services/SettingsManager.ts",
        ".electron/services/pageTranslator.ts",
        ".electron/services/LlmTranslator.ts",
        ".electron/services/BookmarkManager.ts",
        ".electron/services/HistoryManager.ts",
        ".electron/services/PasswordManager.ts",
        ".electron/services/AutofillManager.ts",
        ".electron/services/DownloadStore.ts",
        ".electron/services/TabSessionStore.ts",
        ".electron/services/PermissionBroker.ts",
        ".electron/services/permissionPolicy.ts",
        ".electron/services/windowOpenPolicy.ts",
        ".electron/services/autoUpdateScheduler.ts",
        ".electron/services/HibernationController.ts",
        ".electron/services/LlmsTxtCacheStore.ts",
        ".electron/services/LlmsTxtResolver.ts",
        ".electron/services/StructuredActionInvoker.ts",
        ".electron/services/PageLearner.ts",
        ".electron/ipc/main-handlers.ts",
        ".electron/preload.ts",
      ],
      exclude: ["**/*.d.ts", "**/index.ts"],
      thresholds: {
        lines: 90,
        functions: 90,
        branches: 90,
        statements: 90,
      },
    },
  },
});
