export interface IpcChannels {
  // Renderer → Main
  'tab:create': { url?: string; index?: number };
  'tab:close': { tabId: string };
  'tab:activate': { tabId: string };
  'tab:reorder': { fromIndex: number; toIndex: number };
  'tab:pin': { tabId: string };
  'tab:duplicate': { tabId: string };
  'tab:hibernate': { tabId: string };
  'tab:wake': { tabId: string };
  'tab:mute': { tabId: string };
  'tab:unmute': { tabId: string };
  'navigation:go': { tabId: string; url: string };
  'navigation:back': { tabId: string };
  'navigation:forward': { tabId: string };
  'navigation:reload': { tabId: string; hard?: boolean };
  'navigation:stop': { tabId: string };
  'zoom:set': { tabId: string; level: number };
  'zoom:reset': { tabId: string };
  'find:start': { tabId: string; text: string; caseSensitive?: boolean };
  'find:next': { tabId: string; forward?: boolean };
  'find:stop': { tabId: string };
  'bookmark:add': { url: string; title: string; parentId?: string };
  'bookmark:remove': { bookmarkId: string };
  'bookmark:move': { bookmarkId: string; parentId: string; index: number };
  'bookmark:update': { bookmarkId: string; changes: Partial<import('./browser').Bookmark> };
  'bookmark:getTree': {};
  'bookmark:import': { format: 'netscape-html'; data: string };
  'bookmark:export': { format: 'netscape-html' };
  'history:clear': { range?: 'all' | 'hour' | 'day' | 'week' | 'month' };
  'history:search': { query: string; limit?: number };
  'history:getRecent': { limit?: number };
  'download:pause': { downloadId: string };
  'download:resume': { downloadId: string };
  'download:cancel': { downloadId: string };
  'download:open': { downloadId: string };
  'download:showInFolder': { downloadId: string };
  'download:clearCompleted': {};
  'download:retry': { downloadId: string };
  'settings:get': { key: string };
  'settings:getAll': {};
  'settings:set': { key: string; value: unknown };
  'settings:reset': { key?: string };
  'password:getAll': {};
  'password:save': { entry: import('./browser').PasswordEntry };
  'password:remove': { origin: string; username: string };
  'password:getForOrigin': { origin: string };
  'window:minimize': {};
  'window:maximize': {};
  'window:close': {};
  'window:setFullscreen': { fullscreen: boolean };
  'app:quit': {};
  'app:getVersion': {};
  'app:checkForUpdates': {};
  'devtools:toggle': { tabId: string };
  'devtools:open': { tabId: string; mode?: 'right' | 'bottom' | 'undocked' };
  'print:start': { tabId: string };
  'print:toPDF': { tabId: string; outputPath: string; options?: { marginsType?: number; pageSize?: string; printBackground?: boolean } };
  'permission:respond': { origin: string; permission: PermissionType; allow: boolean };
  'contentSetting:set': { origin: string; setting: ContentSettingType; value: 'allow' | 'block' | 'ask' };
  'contextMenu:clicked': { itemId: string };
  'omnibox:getSuggestions': { query: string; maxResults?: number };
  'autofill:detectFields': { tabId: string; fields: import('./browser').FormField[] };
  'autofill:fillField': { tabId: string; fieldId: string; value: string };
  'autofill:getAddresses': {};
  'autofill:saveAddress': { address: import('./browser').SavedAddress };
  'autofill:removeAddress': { addressId: string };

  // Main → Renderer
  'tab:created': import('./browser').Tab;
  'tab:closed': { tabId: string };
  'tab:activated': { tabId: string };
  'tab:updated': Partial<import('./browser').Tab>;
  'tab:reordered': { tabIds: string[] };
  'tab:hibernated': { tabId: string };
  'tab:woken': { tabId: string };
  'navigation:state': { tabId: string; canGoBack: boolean; canGoForward: boolean; isLoading: boolean; url: string };
  'load:started': { tabId: string; url: string };
  'load:progress': { tabId: string; percent: number };
  'load:finished': { tabId: string; url: string };
  'load:failed': { tabId: string; errorCode: number; errorDescription: string; validatedURL: string };
  'page:title': { tabId: string; title: string };
  'page:favicon': { tabId: string; faviconUrl: string };
  'download:created': import('./browser').DownloadItem;
  'download:updated': Partial<import('./browser').DownloadItem>;
  'download:completed': { downloadId: string };
  'download:failed': { downloadId: string; error: string };
  'settings:changed': { key: string; value: unknown };
  'zoom:changed': { tabId: string; level: number };
  'find:result': import('./browser').FindResult;
  'fullscreen:changed': { isFullscreen: boolean };
  'keyboard:shortcut': { accelerator: string };
  'contextMenu:show': { x: number; y: number; items: import('./browser').ContextMenuItem[] };
  'certificate:error': { url: string; error: string; certificate?: import('./browser').CertificateInfo };
  'permission:request': { origin: string; permission: PermissionType };
  'app:updateAvailable': { version: string };
  'app:updateDownloaded': { version: string };
  'autofill:showDropdown': { tabId: string; fieldId: string; suggestions: import('./browser').AutofillMatch[]; position: { x: number; y: number; width: number; height: number } };
}

type PermissionType = import('./browser').PermissionType;
type ContentSettingType = import('./browser').ContentSettingType;
