/**
 * Pure builders for Pi's on-disk configuration (settings.json, auth.json,
 * and an optional provider-override extension). Kept side-effect free so
 * they can be unit-tested without touching the filesystem; PiConfigWriter
 * does the actual I/O.
 *
 * Pi resolves its config from the directory named by the
 * `PI_CODING_AGENT_DIR` env var (see config.ts → getAgentDir). Horizon
 * points that at an app-local folder and materializes these files from
 * the user's Settings (provider / model / API key / base URL).
 *
 * Provider ids double as auth.json keys for the built-in API-key providers
 * (anthropic, openai, google, …), matching Pi's `providers.md`.
 */

export interface AiProviderConfig {
  /** Pi provider id, e.g. "anthropic", "openai", "google". */
  provider: string;
  /** Default model id; empty → let Pi pick its provider default. */
  model?: string;
  /** API key literal. Stored in auth.json with 0600 perms. */
  apiKey?: string;
  /** Optional custom endpoint (proxy / self-hosted / gateway). */
  baseUrl?: string;
}

/** Filename of the generated provider-override extension, when used. */
export const PROVIDER_OVERRIDE_FILE = "horizon-provider-override.mjs";

/**
 * Build the subset of Pi's settings.json that Horizon manages.
 * `extensions` is threaded through so the writer can register the
 * generated base-URL override. Other settings.json keys are preserved
 * by the writer's read-merge-write.
 */
export function buildPiSettings(
  cfg: AiProviderConfig,
  extensions: string[] = [],
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  if (cfg.provider) out.defaultProvider = cfg.provider;
  if (cfg.model) out.defaultModel = cfg.model;
  if (extensions.length > 0) out.extensions = extensions;
  return out;
}

/**
 * Build auth.json. Returns null when no API key is configured (e.g. the
 * user authenticates Pi via `/login`/OAuth or an external env var), so
 * the writer can leave any existing auth.json untouched.
 */
export function buildPiAuth(
  cfg: AiProviderConfig,
): Record<string, { type: "api_key"; key: string }> | null {
  if (!cfg.provider || !cfg.apiKey) return null;
  return { [cfg.provider]: { type: "api_key", key: cfg.apiKey } };
}

/**
 * Build a tiny Pi extension that overrides the provider's base URL. Pi
 * exposes endpoint overrides only via `pi.registerProvider()` (see
 * custom-provider.md), not via settings.json, so a custom base URL is
 * materialized as a generated extension. Returns null when no base URL
 * is set. Plain JS (no type imports) so Pi's jiti loader needs nothing
 * resolved at runtime.
 */
export function buildProviderOverrideExtension(
  cfg: AiProviderConfig,
): string | null {
  if (!cfg.provider || !cfg.baseUrl) return null;
  const provider = JSON.stringify(cfg.provider);
  const baseUrl = JSON.stringify(cfg.baseUrl);
  return `// Generated by Horizon — do not edit. Overrides the provider base URL.
export default function (pi) {
  pi.registerProvider(${provider}, { baseUrl: ${baseUrl} });
}
`;
}
