/**
 * Pure builders for Pi's on-disk configuration (settings.json, auth.json,
 * and an optional provider-override extension). Kept side-effect free so
 * they can be unit-tested without touching the filesystem; PiConfigWriter
 * does the actual I/O.
 *
 * Pi resolves its config from the directory named by the
 * `PI_CODING_AGENT_DIR` env var (see config.ts → getAgentDir). Horizon
 * points that at an app-local folder and materializes these files from
 * the user's Settings (provider / model / API key / base URL).
 *
 * Provider ids double as auth.json keys for the built-in API-key providers
 * (anthropic, openai, google, …), matching Pi's `providers.md`.
 */

export interface AiProviderConfig {
  /** Pi provider id, e.g. "anthropic", "openai", "google". */
  provider: string;
  /** Default model id; empty → let Pi pick its provider default. */
  model?: string;
  /** API key literal. Stored in auth.json with 0600 perms. */
  apiKey?: string;
  /** Optional custom endpoint (proxy / self-hosted / gateway). */
  baseUrl?: string;
}

/** Filename of the generated provider-override extension, when used. */
export const PROVIDER_OVERRIDE_FILE = "horizon-provider-override.mjs";

/**
 * Scalar settings.json keys Horizon fully owns and rewrites on every spawn.
 * Deleted before the read-merge so clearing a field in the UI removes the
 * stale value (buildPiSettings omits unset keys rather than nulling them).
 * `extensions` is NOT here — it's a shared array where only the generated
 * override entry is Horizon-managed, so the writer reconciles it in place.
 */
export const MANAGED_SETTINGS_KEYS = ["defaultProvider", "defaultModel"] as const;

/**
 * Build the scalar subset of Pi's settings.json that Horizon manages
 * (`defaultProvider` / `defaultModel`). The `extensions` array is NOT
 * emitted here — the writer reconciles it so user/Pi-installed extensions
 * survive. Unset fields are omitted so the writer can drop stale values.
 *
 * @param cfg - The user's provider/model/credential configuration.
 * @returns A partial settings.json object with only the keys that are set.
 */
export function buildPiSettings(
  cfg: AiProviderConfig,
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  if (cfg.provider) out.defaultProvider = cfg.provider;
  if (cfg.model) out.defaultModel = cfg.model;
  return out;
}

/**
 * Build the auth.json entry for the configured provider.
 *
 * @param cfg - The user's provider/model/credential configuration.
 * @returns A single-provider `{ [provider]: { type, key } }` map, or null
 *   when no API key is set (e.g. the user uses `/login`/OAuth or an env
 *   var) so the writer can leave other providers' credentials untouched.
 */
export function buildPiAuth(
  cfg: AiProviderConfig,
): Record<string, { type: "api_key"; key: string }> | null {
  if (!cfg.provider || !cfg.apiKey) return null;
  return { [cfg.provider]: { type: "api_key", key: cfg.apiKey } };
}

/**
 * Build a tiny Pi extension that overrides the provider's base URL. Pi
 * exposes endpoint overrides only via `pi.registerProvider()` (see
 * custom-provider.md), not via settings.json, so a custom base URL is
 * materialized as a generated extension. Plain JS (no type imports) so
 * Pi's jiti loader needs nothing resolved at runtime.
 *
 * @param cfg - The user's provider/model/credential configuration.
 * @returns The extension source, or null when no base URL is configured.
 */
export function buildProviderOverrideExtension(
  cfg: AiProviderConfig,
): string | null {
  if (!cfg.provider || !cfg.baseUrl) return null;
  const provider = JSON.stringify(cfg.provider);
  const baseUrl = JSON.stringify(cfg.baseUrl);
  return `// Generated by Horizon — do not edit. Overrides the provider base URL.
export default function (pi) {
  pi.registerProvider(${provider}, { baseUrl: ${baseUrl} });
}
`;
}
