import { app } from "electron";
import { promises as fs, existsSync } from "fs";
import path from "path";

/**
 * Write a Pi skill for a given site from its llms.txt contents. Skills
 * land at ~/.pi/agent/skills/horizon-<sanitized-host>/SKILL.md and Pi
 * auto-discovers them on next startup.
 *
 * Idempotent — skips if the SKILL.md already exists. Returns the path
 * written (or already present), or null if writing failed.
 */
function truncateText(text: string, maxChars: number): string {
  if (text.length <= maxChars) return text;
  return (
    text.slice(0, maxChars) + "\n\n... [truncated to save token limit] ...\n"
  );
}

export async function writePiSkill(
  origin: string,
  llmsTxt: string,
  llmsFullTxt?: string,
): Promise<string | null> {
  let host: string;
  try {
    host = new URL(origin).host;
  } catch {
    return null;
  }
  const sanitized = host.replace(/[^a-zA-Z0-9._-]/g, "-");
  const skillDir = path.join(
    app.getPath("home"),
    ".pi",
    "agent",
    "skills",
    `horizon-${sanitized}`,
  );
  const skillFile = path.join(skillDir, "SKILL.md");

  if (existsSync(skillFile)) return skillFile;

  const truncatedLlmsTxt = truncateText(llmsTxt, 10000);
  const truncatedLlmsFullTxt = llmsFullTxt
    ? truncateText(llmsFullTxt, 15000)
    : undefined;
  const body = renderSkill(origin, truncatedLlmsTxt, truncatedLlmsFullTxt);
  try {
    await fs.mkdir(skillDir, { recursive: true });
    await fs.writeFile(skillFile, body, "utf8");
    return skillFile;
  } catch {
    return null;
  }
}

function renderSkill(
  origin: string,
  llmsTxt: string,
  llmsFullTxt?: string,
): string {
  const header = [
    "---",
    `name: horizon-${safeName(origin)}`,
    `description: Navigation guide and key references for ${origin}, auto-extracted from llms.txt.`,
    "---",
    "",
    `# ${origin}`,
    "",
    "This skill was generated by Horizon from the site's `llms.txt` /",
    "`llms-full.txt`. Use it when the user is working with this site",
    "and wants context about its structure, APIs, or important pages.",
    "",
    "## Site map (from llms.txt)",
    "",
    llmsTxt.trim(),
    "",
  ];
  if (llmsFullTxt) {
    header.push(
      "## Full reference (from llms-full.txt)",
      "",
      llmsFullTxt.trim(),
      "",
    );
  }
  return header.join("\n");
}

function safeName(origin: string): string {
  try {
    return new URL(origin).host.replace(/[^a-zA-Z0-9._-]/g, "-");
  } catch {
    return origin.replace(/[^a-zA-Z0-9._-]/g, "-");
  }
}
